Rails.application.routes.draw do
  get 'products/', to: 'products#index'
  get 'reviews/', to: 'reviews#index'
  get 'reviews/:id', to: 'reviews#show'
  get 'users/', to: 'users#index'
  get 'product_types/', to: 'product_types#index'
  get 'product_categories/', to: 'product_categories#index'
  get 'skin_concerns/', to: 'skin_concerns#index'
  get 'cart_items/', to: 'cart_items#index'
  get 'product_skin_concerns/', to: 'product_skin_concerns#index'
  # get 'cart_items/index'
  # get 'cart_items/create'
  # get 'cart_items/show'
  # get 'cart_items/update'
  # get 'cart_items/destroy'
  # get 'skin_concerns/index'
  # get 'skin_concerns/create'
  # get 'skin_concerns/show'
  # get 'skin_concerns/update'
  # get 'skin_concerns/destroy'
  # get 'reviews/index'
  # get 'reviews/create'
  # get 'reviews/show'
  # get 'reviews/update'
  # get 'reviews/destroy'
  # get 'users/index'
  # get 'users/create'
  # get 'users/show'
  # get 'users/update'
  # get 'users/destroy'
  # get 'product_skin_concerns/index'
  # get 'product_skin_concerns/create'
  # get 'product_skin_concerns/show'
  # get 'product_skin_concerns/update'
  # get 'product_skin_concerns/destroy'
  # get 'product_categories/index'
  # get 'product_categories/create'
  # get 'product_categories/show'
  # get 'product_categories/update'
  # get 'product_categories/destroy'
  # get 'product_types/index'
  # get 'product_types/create'
  # get 'product_types/show'
  # get 'product_types/update'
  # get 'product_types/destroy'
  # get 'products/index'
  # get 'products/create'
  # get 'products/show'
  # get 'products/update'
  # get 'products/destroy'
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
